title: ShardaLearningCenter
email: s.learnkarma@gmail.com
description: >- 
  Learn to code by building real projects. Fast. Practical. No fluff.
baseurl: "" 
url: "shaardalearningcenter.github.io" 
theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap
# 👇 Add this to show menu in navbar
minima:
  skin: auto
  social_links: []
  navigation:
    - title: "Home"
      url: "/"
    - title: "Python Bootcamp"
      url: "/python-bootcamp/"
    - title: "Golang Bootcamp"
      url: "/golang-bootcamp/"
    - title: "Blog"
      url: "/blog/"
    - title: "About"
      url: "/about/"
    - title: "DSA CheatSheet"
      url: "/dsa-cheatsheet"
    
